apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: trustvote-app-tls
spec:
  secretName: trustvote-app
  issuerRef:
    name: issuer-config
    kind: ClusterIssuer
  commonName: trustvote.app
  dnsNames:
    - trustvote.app
    - www.trustvote.app
