FROM node:14-alpine

RUN mkdir /srv/be-trustvote
WORKDIR /srv/be-trustvote

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

CMD ["sh", "-c", "node index.js"]
# CMD ["sh", "-c", "npm run migrate && node index.js"]
